locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: view_history
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: View History
        index: 0
        uses: -1
      - mode: text
        value: View history
        index: 0
        uses: 1
      - mode: text
        value: view history
        index: 0
        uses: 0
      - mode: value
        value: View History
        index: 0
        uses: 0
      - mode: value
        value: View history
        index: 0
        uses: 0
      - mode: value
        value: view history
        index: 0
        uses: 0
