actions:
  - verb: fill
    name: search
    locators:
      - mode: name
        value: search
        index: 0
        uses: 2
  - verb: type
    name: enter
    locators:
      -
locators:
  inclusions:
    -
  exclusions:
    -
